import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseCapture,validate,buildFrame,panelSelection,contains} from '../model.js';
import {luaExport,selectionJSON} from '../export.js';
import {exampleCapture} from '../example.js';
const p=(x,y)=>({kind:'Vec2',x,y}),color={kind:'Color',r:255,g:0,b:0,a:255};
function capture(calls){return {version:2,screen:{width:1920,height:1080},calls:calls.map((c,i)=>({id:i+1,frame:1,source:1,args:[],...c})),sources:['example.lua:10: draw'],resources:{}};}
test('synthetic example validates and has grouped parts',()=>{const data=validate(exampleCapture()),frame=buildFrame(data,1);assert(frame.parts.length>10);assert.equal(frame.helpers.length,1);assert(panelSelection(frame,frame.parts[3].call.id).size>10);});
test('invalid JSON, duplicate identifiers and unsupported screen size fail cleanly',()=>{assert.throws(()=>parseCapture('{broken'));assert.throws(()=>validate(capture([{id:1},{id:1}])));assert.throws(()=>validate({...capture([]),screen:{width:Infinity,height:20}}));});
test('clip and alpha state affect visibility and hit bounds',()=>{const data=capture([{method:'PushClip',args:[p(10,10),p(50,50)]},{method:'FilledRect',args:[p(0,0),p(100,100),color]},{method:'SetGlobalAlpha',args:[0]},{method:'FilledRect',args:[p(20,20),p(30,30),color]},{method:'ResetGlobalAlpha'},{method:'PopClip'}]);const f=buildFrame(data,1);assert.deepEqual(f.parts[0].effective,[10,10,40,40]);assert(!contains(f.parts[0].effective,{x:1,y:1}));assert.equal(f.parts.length,1);});
test('horizontal and vertical lines are selectable',()=>{const f=buildFrame(capture([{method:'Line',args:[p(0,1),p(100,1),color]},{method:'Line',args:[p(1,0),p(1,100),color]}]),1);assert.equal(f.parts.length,2);});
test('RenderRT children are not wrongly placed on screen',()=>{const f=buildFrame(capture([{method:'RenderRT'},{method:'FilledRect',parentId:1,args:[p(0,0),p(40,40),color]}]),1);assert.equal(f.parts.length,0);assert(f.warnings.length);});
test('LIB_RENDER text and image argument layouts are adapted',()=>{const f=buildFrame(capture([{library:'LIB_RENDER',method:'text',args:[3,14,p(40,50),'Test',color]},{library:'LIB_RENDER',method:'image',args:['icon.png',p(5,8),p(32,32),false,color]}]),1);assert.equal(f.parts[0].args[2],'Test');assert.deepEqual(f.parts[1].bounds,[5,8,32,32]);});
test('Renderer v1 tracks SetDrawColor and xywh geometry',()=>{const d=capture([{library:'Renderer',method:'SetDrawColor',args:[4,5,6,128]},{library:'Renderer',method:'DrawFilledRect',args:[10,20,100,50]},{library:'Renderer',method:'DrawImageCentered',args:[7,50,60,30,20]}]);const f=buildFrame(d,1);assert.deepEqual(f.parts[0].bounds,[10,20,100,50]);assert.equal(f.parts[0].color.a,128);assert.deepEqual(f.parts[1].bounds,[35,50,30,20]);});
test('legacy font metadata controls preview size and export library',()=>{const d=capture([{library:'Renderer',method:'DrawText',args:[7,10,20,'Legacy']}]);d.resources.font={library:'Renderer',method:'LoadFont',result:7,args:['Tahoma',22,0,500]};const f=buildFrame(d,1);assert.equal(f.parts[0].args[1],22);const out=luaExport(d,f,new Set([1]));assert(out.code.includes('Renderer.LoadFont'));assert(out.code.includes('Renderer.DrawText(font1, SX(10), SY(20), "Legacy")'));});
test('export expands helpers, retains clip state, and is re-importable',()=>{const d=exampleCapture(),f=buildFrame(d,1),ids=new Set([1]);const out=luaExport(d,f,ids);assert(out.code.includes('Render.PushClip'));assert(out.code.includes('Render.PopClip'));assert(!out.code.includes('Example.DrawPanel('));assert(out.code.includes('Render.LoadFont'));assert(out.code.includes('return { OnDraw = drawSelection }'));assert(parseCapture(selectionJSON(d,f,ids)).calls.length>10);});
test('unreconstructable callback values produce warnings, never execution',()=>{const d=capture([{method:'UnknownDraw',args:[{kind:'function'}]}]),f=buildFrame(d,1);const out=luaExport(d,f,new Set([1]));assert.equal(out.count,0);assert(out.warnings.some(w=>w.includes('function')));});
test('unknown helpers remain in raw calls instead of guessed geometry',()=>{const f=buildFrame(capture([{library:'XHelpers.XRender',method:'DrawAlert',args:[123]}]),1);assert.equal(f.unmapped.length,1);assert.equal(f.parts.length,0);});
test('selected child JSON drops absent parent references',()=>{const d=exampleCapture(),f=buildFrame(d,1);assert.doesNotThrow(()=>parseCapture(selectionJSON(d,f,new Set([2]))));});
